name: Format

on: push

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [./client, ./server]
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup
        uses: actions/setup-node@master
        with:
          node-version: "14"

      - name: dependencies
        run: npm ci
        working-directory: ${{ matrix.dir }}

      - name: format
        run: npx prettier --write .
        working-directory: ${{ matrix.dir }}

      - name: commit
        uses: stefanzweifel/git-auto-commit-action@master
        with:
          commit_message: Apply formatting changes
